SELECT
    a.AUTHOR_ID,
    b.AUTHOR_NAME,
    a.CATEGORY,
    SUM(a.PRICE * c.SALES) as SALES
FROM
    BOOK as a
    JOIN AUTHOR as b ON a.AUTHOR_ID = b.AUTHOR_ID
    JOIN BOOK_SALES as c ON a.BOOK_ID = c.BOOK_ID
WHERE
    c.SALES_DATE LIKE '2022-01-%'
GROUP BY
    a.AUTHOR_ID, a.CATEGORY
ORDER BY a.AUTHOR_ID, a.CATEGORY DESC;