SELECT
    b.USER_ID, b.NICKNAME, 
    SUM(PRICE) AS TOTAL_SALES
FROM
    USED_GOODS_BOARD as a
    JOIN USED_GOODS_USER as b ON a.WRITER_ID = b.USER_ID
WHERE STATUS = 'DONE'
    
GROUP BY a.WRITER_ID
HAVING SUM(PRICE) >= 700000

ORDER BY TOTAL_SALES;